ALTER TABLE settings ADD COLUMN body_font_weight INTEGER NOT NULL DEFAULT 400;
ALTER TABLE settings ADD COLUMN heading_font_weight INTEGER NOT NULL DEFAULT 600;
ALTER TABLE settings ADD COLUMN menu_font_weight INTEGER NOT NULL DEFAULT 500;
ALTER TABLE settings ADD COLUMN submenu_font_weight INTEGER NOT NULL DEFAULT 500;
